### ISSUE TITLE
Docker hub 上没有1.1.1的tag

### ISSUE THREAD

**Issue by mgcnrx11** [DeerCloud/docker-snell#3]
https://hub.docker.com/r/deercloud/snell/tags

在Docker hub上并没有1.1.1的tag，是否忘了发布该tag

**Comment by metowolf** [comment]
可以使用 https://hub.docker.com/r/metowolf/snell/tags
项目现迁移到 https://github.com/metowolf/docker-snell

**Comment by Felix2yu** [comment]
latest就是1.1.1

**Comment by mgcnrx11** [comment]
好的谢谢
